export const INSTALLED_SYSTEM_PROFILES_SUBDIRECTORY_DIRECTORY =
  "/resources/profiles";
export const LOADED_SYSTEM_PROFILES_SUBDIRECTORY_DIRECTORY = "/system";
export const LOADED_USER_PROFILES_SUBDIRECTORY_DIRECTORY = "/user/default";
export const LOADED_USER_PROFILES_BASE_SUBDIRECTORY_DIRECTORY = "/base";
export const LOADED_USER_PROFILES_MACHINE_SUBDIRECTORY_DIRECTORY = "/machine";
