// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigDetails } from "./ConfigDetails";
import type { ErrWan } from "./ErrWan";

export type AnalysisMessageDetails = { config_details: ConfigDetails, message: ErrWan, };
