// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfigDetails = { name: string, file: string, family: string | null, location: string, config_type: string, };
