// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigErrorMessage } from "./ConfigErrorMessage";
import type { ConfigWarningMessage } from "./ConfigWarningMessage";

export type ConfigAnalysisMessage = { "error": ConfigErrorMessage } | { "warning": ConfigWarningMessage };
