// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrType } from "./ErrType";

export type ErrWan = { text: string, type: ErrType, };
