// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilamentJsonSchema = { name: string, type: string | null, inherits: string | null, instantiation: string | null, } & Record<string, unknown>;
