// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MinPrinterVariantJsonSchema = { name: string, type: string | null, nozzle_diameter: Array<string> | null, inherits: string | null, instantiation: string | null, };
