// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrinterModelJsonSchema = { name: string, type: string, nozzle_diameter: string, family: string, } & Record<string, unknown>;
