// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigNameAndPath } from "./ConfigNameAndPath";

export type VendorJsonSchema = { name: string, version: string | null, machine_model_list: Array<ConfigNameAndPath> | null, process_list: Array<ConfigNameAndPath> | null, filament_list: Array<ConfigNameAndPath> | null, machine_list: Array<ConfigNameAndPath> | null, } & Record<string, unknown>;
